select count('a'), B.BETNAME, R.STATUS
from ABETS B, ALL_RUNNERS R
where B.MARKETID=R.MARKETID
and B.SELECTIONID = R.SELECTIONID
and B.BETNAME like 'BACK%'
and B.BETPLACED >= '2015-08-30'
and R.STATUS in ('WINNER','LOSER')
group by B.BETNAME, R.STATUS
order by B.BETNAME, R.STATUS