-----------------------------------------------------
-- This file is AUTOGENERATED by                     
-- /home/bnl/bnlbot/botstart/bot-1-0/script/tcl/make_table_package.tcl at                                       
--9.6-10510                                          
----CHANGES HERE WILL BE LOST NEXT GENERATE!!!!----- 
-----------DO NOT EDIT THIS FILE!!!!---------------- 
-----------------------------------------------------



pragma Warnings(Off);
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Sattmate_Types, Sattmate_Calendar, Sql, Simple_List_Class;

package Table_Dryresults is

  use Sattmate_Types, Sattmate_Calendar;

  type Data_Type is record
      Marketid :    Integer_4  := 0 ; -- Primary Key
      Selectionid :    Integer_4  := 0 ; -- Primary Key
  end record;
  Empty_Data : Table_Dryresults.Data_Type;
  -- 
  -- Table name as string 
  --
  Table_Dryresults_Name : constant String := "DRYRESULTS";
  Table_Dryresults_Set_Name : constant String := "DRYRESULTS_SET";
  Table_Dryresults_Row_Name : constant String := "DRYRESULTS_ROW";
  -- 
  -- Column names as strings 
  --
  Marketid_Name : constant String := "MARKETID";
  Selectionid_Name : constant String := "SELECTIONID";
  -- 
  -- Column names as enumerator literals 
  --
  type Column_Type is (
        Marketid,
        Selectionid);

  package Dryresults_List_Pack is new Simple_List_Class(Table_Dryresults.Data_Type);

  -- Procedures for DBMS DEF
  -- Primary key
  function Get(Stm : in Sql.Statement_Type) return Table_Dryresults.Data_Type;
  --------------------------------------------
  procedure Read(Data       : in out Table_Dryresults.Data_Type;
                 End_Of_Set : in out Boolean);
  --------------------------------------------
  function Is_Existing(Marketid : Integer_4;
                       Selectionid : Integer_4) return Boolean;
  --------------------------------------------
  function Get(Marketid : Integer_4;
                       Selectionid : Integer_4) return Table_Dryresults.Data_Type;
  --------------------------------------------

  procedure Read_List(Stm  : in     Sql.Statement_Type;
                      List : in out Dryresults_List_Pack.List_Type;
                      Max  : in     Integer_4 := Integer_4'Last);
  --------------------------------------------
  procedure Read_All(List  : in out Dryresults_List_Pack.List_Type;
                     Order : in     Boolean := False;
                     Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------
  procedure Delete(Data : in Table_Dryresults.Data_Type);
  --------------------------------------------
  procedure Insert(Data : in out Table_Dryresults.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  -- Primary keys, when several fields

  procedure Read_I1_Marketid(Data  : in     Table_Dryresults.Data_Type;
                       List  : in out Dryresults_List_Pack.List_Type;
                       Order : in     Boolean := False;
                       Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------

  procedure Delete_I1_Marketid(Data  : in     Table_Dryresults.Data_Type);
  --------------------------------------------

  function Is_Existing_I1(
                 Marketid     : in Integer_4 )      return Boolean;


  -- Procedures for all DBMS

  function To_String(Data : in Table_Dryresults.Data_Type) return String;

end Table_Dryresults ;
