-----------------------------------------------------
-- This file is AUTOGENERATED by                     
-- /home/bnl/bnlbot/botstart/bot-1-0/script/tcl/make_table_package.tcl at                                       
--9.6-10510                                          
----CHANGES HERE WILL BE LOST NEXT GENERATE!!!!----- 
-----------DO NOT EDIT THIS FILE!!!!---------------- 
-----------------------------------------------------



pragma Warnings(Off);
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Sattmate_Types, Sattmate_Calendar, Sql, Simple_List_Class;

package Table_Aprices is

  use Sattmate_Types, Sattmate_Calendar;

  type Data_Type is record
      Marketid :    String (1..11) := (others => ' ') ; -- Primary Key
      Selectionid :    Integer_4  := 0 ; -- Primary Key
      Pricets :    Time_Type  := Time_Type_First ; --
      Status :    String (1..50) := (others => ' ') ; -- non unique index 3
      Totalmatched :    Float_8  := 0.0 ; --
      Backprice :    Float_8  := 0.0 ; -- non unique index 4
      Layprice :    Float_8  := 0.0 ; --
      Ixxlupd :    String (1..15) := (others => ' ') ; --
      Ixxluts :    Time_Type  := Time_Type_First ; --
  end record;
  Empty_Data : Table_Aprices.Data_Type;
  -- 
  -- Table name as string 
  --
  Table_Aprices_Name : constant String := "APRICES";
  Table_Aprices_Set_Name : constant String := "APRICES_SET";
  Table_Aprices_Row_Name : constant String := "APRICES_ROW";
  -- 
  -- Column names as strings 
  --
  Marketid_Name : constant String := "MARKETID";
  Selectionid_Name : constant String := "SELECTIONID";
  Pricets_Name : constant String := "PRICETS";
  Status_Name : constant String := "STATUS";
  Totalmatched_Name : constant String := "TOTALMATCHED";
  Backprice_Name : constant String := "BACKPRICE";
  Layprice_Name : constant String := "LAYPRICE";
  Ixxlupd_Name : constant String := "IXXLUPD";
  Ixxluts_Name : constant String := "IXXLUTS";
  -- 
  -- Column names as enumerator literals 
  --
  type Column_Type is (
        Marketid,
        Selectionid,
        Pricets,
        Status,
        Totalmatched,
        Backprice,
        Layprice,
        Ixxlupd,
        Ixxluts);

  package Aprices_List_Pack is new Simple_List_Class(Table_Aprices.Data_Type);

  -- Procedures for DBMS DEF
  -- Primary key
  function Get(Stm : in Sql.Statement_Type) return Table_Aprices.Data_Type;
  --------------------------------------------
  procedure Read(Data       : in out Table_Aprices.Data_Type;
                 End_Of_Set : in out Boolean);
  --------------------------------------------
  function Is_Existing(Marketid : String;
                       Selectionid : Integer_4) return Boolean;
  --------------------------------------------
  function Get(Marketid : String;
                       Selectionid : Integer_4) return Table_Aprices.Data_Type;
  --------------------------------------------

  procedure Read_List(Stm  : in     Sql.Statement_Type;
                      List : in out Aprices_List_Pack.List_Type;
                      Max  : in     Integer_4 := Integer_4'Last);
  --------------------------------------------
  procedure Read_All(List  : in out Aprices_List_Pack.List_Type;
                     Order : in     Boolean := False;
                     Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------
  procedure Delete(Data : in Table_Aprices.Data_Type);
  --------------------------------------------
  procedure Update(Data : in out Table_Aprices.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  procedure Insert(Data : in out Table_Aprices.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  procedure Delete_Withcheck(Data : in Table_Aprices.Data_Type);
  --------------------------------------------
  procedure Update_Withcheck(Data : in out Table_Aprices.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  -- Primary keys, when several fields

  procedure Read_I1_Marketid(Data  : in     Table_Aprices.Data_Type;
                       List  : in out Aprices_List_Pack.List_Type;
                       Order : in     Boolean := False;
                       Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------

  procedure Delete_I1_Marketid(Data  : in     Table_Aprices.Data_Type);
  --------------------------------------------

  function Is_Existing_I1(
                 Marketid     : in String )      return Boolean;

  -- Index 

  procedure Read_Backprice(Data  : in     Table_Aprices.Data_Type;
                       List  : in out Aprices_List_Pack.List_Type;
                       Order : in     Boolean := False;
                       Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------

  procedure Read_One_Backprice(Data       : in out Table_Aprices.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  function Count_Backprice(Data : Table_Aprices.Data_Type) return Integer_4;
  --------------------------------------------


  procedure Delete_Backprice(Data  : in     Table_Aprices.Data_Type);
  --------------------------------------------

  -- Index 

  procedure Read_Status(Data  : in     Table_Aprices.Data_Type;
                       List  : in out Aprices_List_Pack.List_Type;
                       Order : in     Boolean := False;
                       Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------

  procedure Read_One_Status(Data       : in out Table_Aprices.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  function Count_Status(Data : Table_Aprices.Data_Type) return Integer_4;
  --------------------------------------------


  procedure Delete_Status(Data  : in     Table_Aprices.Data_Type);
  --------------------------------------------


  -- Procedures for all DBMS

  function To_String(Data : in Table_Aprices.Data_Type) return String;

end Table_Aprices ;
