
-----------------------------------------------------
-- This file is AUTOGENERATED by                     
-- c:/bnl/svn/wcs-std/sattmate/script/local/make_table_package.tcl at                                       
--9.6-10510                                          
----CHANGES HERE WILL BE LOST NEXT GENERATE!!!!----- 
-----------DO NOT EDIT THIS FILE!!!!---------------- 
-----------------------------------------------------




pragma Warnings(Off);
with  General_Routines, Text_Io;
with Ada.Strings.Fixed;

package body Table_Dry_runners is

  Stm_Select,
  Stm_Delete,
  Stm_Update,
  Stm_Insert,
  Stm_Select_All,
  Stm_Select_All_O  : Sql.Statement_Type;


  -- Primary key, if several fields
  Stm_Select_I1_Market_id_O,
  Stm_Select_I1_Market_id,
  Stm_Delete_I1_Market_id : Sql.Statement_Type; 


  -- Procedures for DBMS DEF
  -- Primary key
  function Get(Stm : in Sql.Statement_Type) return Table_Dry_runners.Data_Type is
    Data : Table_Dry_runners.Data_Type;
  begin
    if not Sql.Is_Null(Stm, "MARKET_ID") then
      Sql.Get(Stm, "MARKET_ID", Data.Market_id);
    else
      Data.Market_id := 0;
    end if;
    if not Sql.Is_Null(Stm, "SELECTION_ID") then
      Sql.Get(Stm, "SELECTION_ID", Data.Selection_id);
    else
      Data.Selection_id := 0;
    end if;
    if not Sql.Is_Null(Stm, "INDEX") then
      Sql.Get(Stm, "INDEX", Data.Index);
    else
      Data.Index := 0;
    end if;
    if not Sql.Is_Null(Stm, "BACK_PRICE") then
      Sql.Get(Stm, "BACK_PRICE", Data.Back_price);
    else
      Data.Back_price := 0.0;
    end if;
    if not Sql.Is_Null(Stm, "LAY_PRICE") then
      Sql.Get(Stm, "LAY_PRICE", Data.Lay_price);
    else
      Data.Lay_price := 0.0;
    end if;
    if not Sql.Is_Null(Stm, "RUNNER_NAME") then
      Sql.Get(Stm, "RUNNER_NAME", Data.Runner_name);
    else
      Data.Runner_name := (others => ' ');
    end if;
  return Data;
  end Get;
---------------------------------------------

  function Get(Market_id : Integer_4;
                       Selection_id : Integer_4) return Table_Dry_runners.Data_Type is
    Data       : Table_Dry_runners.Data_Type;
    End_Of_Set : Boolean := True;
  begin
    Data.Market_id := Market_id;
    Data.Selection_id := Selection_id;
    Read(Data, End_Of_Set);
    return Data;
  end Get;
--------------------------------------------

  procedure Read_All(List  : in out Dry_runners_List_Pack.List_Type;
                     Order : in     Boolean := False;
                     Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := (Sql.Transaction_Status = Sql.None);
    Transaction  : Sql.Transaction_Type;
  begin
    if Start_Trans then Sql.Start_Read_Write_Transaction(Transaction); end if;
    if Order then
      Sql.Prepare(Stm_Select_All_O, "select * from DRY_RUNNERS order by MARKET_ID, SELECTION_ID");
      Read_List(Stm_Select_All_O, List, Max);
    else
      Sql.Prepare(Stm_Select_All, "select * from DRY_RUNNERS");
      Read_List(Stm_Select_All, List, Max);
    end if;
    if Start_Trans then Sql.Commit(Transaction); end if;
  end Read_All;
--------------------------------------------


  procedure Read_List(Stm  : in     Sql.Statement_Type;
                      List : in out Dry_runners_List_Pack.List_Type;
                      Max  : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Count       : Integer_4 := 0;
    Data        : Table_Dry_runners.Data_Type;
    Eos         : Boolean := False;
    Start_Trans : constant Boolean := (Sql.Transaction_Status = Sql.None);
    Transaction  : Sql.Transaction_Type;
  begin
    if Start_Trans then Sql.Start_Read_Write_Transaction(Transaction); end if;
    Sql.Open_Cursor(Stm);
    loop
      Sql.Fetch(Stm, Eos); 
      exit when Eos or Count > Max;
      Data := Get(Stm);
      Dry_runners_List_Pack.Insert_At_Tail(List, Data);
      Count := Count +1;
    end loop;
    Sql.Close_Cursor(Stm);
    if Start_Trans then Sql.Commit(Transaction); end if;
  end Read_List;
--------------------------------------------

  function Is_Existing(Market_id : Integer_4;
                       Selection_id : Integer_4) return Boolean is
    Data       : Table_Dry_runners.Data_Type;
    End_Of_Set : Boolean := True;
  begin
    Data.Market_id := Market_id;
    Data.Selection_id := Selection_id;
    Read(Data, End_Of_Set);
    return not End_Of_Set;
  end Is_Existing;
--------------------------------------------

  procedure Read(Data       : in out Table_Dry_runners.Data_Type;
                 End_Of_Set : in out Boolean) is
    use Sql;
    Start_Trans   : constant Boolean := (Sql.Transaction_Status = Sql.None);
    Transaction   : Sql.Transaction_Type;
  begin
    if Start_Trans then Sql.Start_Read_Write_Transaction(Transaction); end if;
    Sql.Prepare(Stm_Select, " select * from DRY_RUNNERS " & 
            "where MARKET_ID=:MARKET_ID" &
            " and SELECTION_ID=:SELECTION_ID" ) ;
    Sql.Set(Stm_Select, "MARKET_ID", Data.Market_id);
    Sql.Set(Stm_Select, "SELECTION_ID", Data.Selection_id);

    Sql.Open_Cursor(Stm_Select);
    Sql.Fetch(Stm_Select, End_Of_Set);
    if not End_Of_Set then
      Data := Get(Stm_Select);
    end if;
    Sql.Close_Cursor(Stm_Select);
    if Start_Trans then Sql.Commit(Transaction); end if;
  end Read;
---------------------------------------------

  procedure Delete(Data : in Table_Dry_runners.Data_Type) is
  begin
    Sql.Prepare(Stm_Delete, " delete from DRY_RUNNERS " & 
            "where MARKET_ID=:MARKET_ID" &
            " and SELECTION_ID=:SELECTION_ID" ) ;
    Sql.Set(Stm_Delete, "MARKET_ID", Data.Market_id);
    Sql.Set(Stm_Delete, "SELECTION_ID", Data.Selection_id);

    Sql.Execute(Stm_Delete);
  end Delete;
--------------------------------------------

  procedure Update(Data : in out Table_Dry_runners.Data_Type; Keep_Timestamp : in Boolean := False) is
    Now     : Sattmate_Calendar.Time_Type := Sattmate_Calendar.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    Sql.Prepare(Stm_Update, "update DRY_RUNNERS set " &
            "INDEX=:INDEX," &
            "BACK_PRICE=:BACK_PRICE," &
            "LAY_PRICE=:LAY_PRICE," &
            "RUNNER_NAME=:RUNNER_NAME " &
            "where MARKET_ID=:MARKET_ID " &
            "and SELECTION_ID=:SELECTION_ID " ) ;
    Sql.Set(Stm_Update, "MARKET_ID",Data.Market_id);
    Sql.Set(Stm_Update, "SELECTION_ID",Data.Selection_id);
    if Data.Index = 0 then
      Sql.Set_Null(Stm_Update, "INDEX");
    else
      Sql.Set(Stm_Update, "INDEX",Data.Index);
    end if;
    Sql.Set(Stm_Update, "BACK_PRICE",Data.Back_price);
    Sql.Set(Stm_Update, "LAY_PRICE",Data.Lay_price);
    Sql.Set(Stm_Update, "RUNNER_NAME",Data.Runner_name);

    Sql.Execute(Stm_Update);
  end Update;
--------------------------------------------

  procedure Insert(Data : in out Table_Dry_runners.Data_Type; Keep_Timestamp : in Boolean := False) is
    Now     : Sattmate_Calendar.Time_Type := Sattmate_Calendar.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    if not Keep_Timestamp then
      null; --for tables without IXX*
    end if;
    Sql.Prepare(Stm_Insert, "insert into DRY_RUNNERS values (" &
            ":MARKET_ID, " &
            ":SELECTION_ID, " &
            ":INDEX, " &
            ":BACK_PRICE, " &
            ":LAY_PRICE, " &
            ":RUNNER_NAME) " ) ;
    Sql.Set(Stm_Insert, "MARKET_ID",Data.Market_id);
    Sql.Set(Stm_Insert, "SELECTION_ID",Data.Selection_id);
    if Data.Index = 0 then
      Sql.Set_Null(Stm_Insert, "INDEX");
    else
      Sql.Set(Stm_Insert, "INDEX",Data.Index);
    end if;
    Sql.Set(Stm_Insert, "BACK_PRICE",Data.Back_price);
    Sql.Set(Stm_Insert, "LAY_PRICE",Data.Lay_price);
    Sql.Set(Stm_Insert, "RUNNER_NAME",Data.Runner_name);

    Sql.Execute(Stm_Insert);
  end Insert;
--------------------------------------------

  -- Primary key, when several fields

  procedure Read_I1_Market_id(Data  : in     Table_Dry_runners.Data_Type;
                       List  : in out Dry_runners_List_Pack.List_Type;
                       Order : in     Boolean := False;
                       Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := (Sql.Transaction_Status = Sql.None);
    Transaction : Sql.Transaction_Type;
  begin
    if (Start_Trans) then Sql.Start_Read_Write_Transaction(Transaction); end if;
    if Order then
      Sql.Prepare(Stm_Select_I1_Market_id_O, " select * from DRY_RUNNERS " & 
            "where MARKET_ID=:MARKET_ID" &
            " order by MARKET_ID, SELECTION_ID"); 
      Sql.Set(Stm_Select_I1_Market_id_O, "MARKET_ID", Data.Market_id);
 
      Read_List(Stm_Select_I1_Market_id_O, List, Max);
    else
      Sql.Prepare(Stm_Select_I1_Market_id, " select * from DRY_RUNNERS " & 
            "where MARKET_ID=:MARKET_ID" ) ; 
      Sql.Set(Stm_Select_I1_Market_id, "MARKET_ID", Data.Market_id);
 
      Read_List(Stm_Select_I1_Market_id, List, Max);
    end if;
    if (Start_Trans) then Sql.Commit(Transaction); end if;
  end Read_I1_Market_id;
  --------------------------------------------

  procedure Delete_I1_Market_id(Data  : in     Table_Dry_runners.Data_Type) is
  begin
      Sql.Prepare(Stm_Delete_I1_Market_id, " delete from DRY_RUNNERS " & 
            "where MARKET_ID=:MARKET_ID" ) ; 
      Sql.Set(Stm_Delete_I1_Market_id, "MARKET_ID", Data.Market_id);
 
    Sql.Execute(Stm_Delete_I1_Market_id);
  end Delete_I1_Market_id;
  --------------------------------------------

  -- Procedures for all DBMS


  function Date_To_String(Date : in Sattmate_Calendar.Time_Type) return String is
    package Integer_2_Io is new Text_Io.Integer_Io(Integer_2);
    Date_String : String(1..10) := "yyyy-mm-dd";
  begin
    Integer_2_Io.Put(Date_String(9..10), Date.Day);
    Integer_2_Io.Put(Date_String(6..7), Date.Month);
    Integer_2_Io.Put(Date_String(1..4), Date.Year);
    if Date_String(9) = ' ' then Date_String(9) := '0'; end if;
    if Date_String(6) = ' ' then Date_String(6) := '0'; end if;
    return Date_String;
  end Date_To_String;
--------------------------------------------

  function To_String(Data : in Table_Dry_runners.Data_Type) return String is
  begin
    return
          " Market_id = " & Integer_4'Image(Data.Market_id) &
          " Selection_id = " & Integer_4'Image(Data.Selection_id) &
          " Index = " & Integer_4'Image(Data.Index) &
          " Back_price = " &  General_Routines.F8_To_String(Data.Back_price) &
          " Lay_price = " &  General_Routines.F8_To_String(Data.Lay_price) &
          " Runner_name = " & General_Routines.Skip_Trailing_Blanks(Data.Runner_name) &
          "";
  end To_String;
--------------------------------------------


end Table_Dry_runners ;

