 
  
#define _GNU_SOURCE  
//#include <sys/types.h>
//#include <sys/wait.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/fcntl.h>

int	main() {

  printf("-- Autogenerated file. Do not Edit! Change in c_contants.c instead. \n\n");
  printf("with Interfaces.C;\n\n");
  printf("package C_Constants is\n");
  printf("  O_RDONLY    : constant Interfaces.C.Int := %d; -- open for reading only\n",O_RDONLY);
  printf("  O_WRONLY    : constant Interfaces.C.Int := %d; -- open for writing only\n",O_WRONLY);
  printf("  O_RDWR      : constant Interfaces.C.Int := %d; -- open for reading and writing\n",O_RDWR);
  printf("  O_CREAT     : constant Interfaces.C.Int := %d; -- no file? create it\n",O_CREAT);
  printf("  O_EXCL      : constant Interfaces.C.Int := %d; -- lock file (see below)\n",O_EXCL);
  printf("  O_NOCTTY    : constant Interfaces.C.Int := %d; -- if tty, don't acquire it\n",O_NOCTTY);
  printf("  O_TRUNC     : constant Interfaces.C.Int := %d; -- file exists? truncate it\n",O_TRUNC);
  printf("  O_APPEND    : constant Interfaces.C.Int := %d; -- file exists? move to end\n",O_APPEND);
  printf("  O_NONBLOCK  : constant Interfaces.C.Int := %d; -- if pipe, don't wait for data\n",O_NONBLOCK);
  printf("  O_SYNC      : constant Interfaces.C.Int := %d; -- don't cache writes\n",O_SYNC);
  printf("  O_ASYNC     : constant Interfaces.C.Int := %d; -- async. IO via SIGIO\n",O_ASYNC);
  printf("  O_DIRECT    : constant Interfaces.C.Int := %d; -- direct disk access\n",O_DIRECT);
  printf("  O_LARGEFILE : constant Interfaces.C.Int := %d; -- not implemented in Linux (yet)\n",O_LARGEFILE);
  printf("  O_DIRECTORY : constant Interfaces.C.Int := %d; -- error if file isn't a dir\n",O_DIRECTORY);
  printf("  O_NOFOLLOW  : constant Interfaces.C.Int := %d; -- if sym link, open link itself\n",O_NOFOLLOW);
  
  
  printf("  F_RDLCK  : constant Interfaces.C.Int := %d; -- read lock\n",F_RDLCK);
  printf("  F_WRLCK  : constant Interfaces.C.Int := %d; -- write lock\n",F_WRLCK);
  printf("  F_UNLCK  : constant Interfaces.C.Int := %d; -- unlock (remove a lock)\n",F_UNLCK);
  printf("  F_EXLCK  : constant Interfaces.C.Int := %d; -- exclusive lock\n",F_EXLCK);
  printf("  F_SHLCK  : constant Interfaces.C.Int := %d; -- shared lock\n",F_SHLCK);
  
  printf("  F_DUPFD  : constant Interfaces.C.Int := %d; --\n",F_DUPFD);
  printf("  F_GETFD  : constant Interfaces.C.Int := %d; --\n",F_GETFD);
  printf("  F_SETFD  : constant Interfaces.C.Int := %d; --\n",F_SETFD);
  printf("  F_GETFL  : constant Interfaces.C.Int := %d; --\n",F_GETFL);
  printf("  F_SETFL  : constant Interfaces.C.Int := %d; --\n",F_SETFL);
  printf("  F_GETLK  : constant Interfaces.C.Int := %d; --\n",F_GETLK);
  printf("  F_SETLK  : constant Interfaces.C.Int := %d; --\n",F_SETLK);
  printf("  F_SETLKW : constant Interfaces.C.Int := %d; --\n",F_SETLKW);
  printf("  F_SETOWN : constant Interfaces.C.Int := %d; --\n",F_SETOWN);
  printf("  F_GETOWN : constant Interfaces.C.Int := %d; --\n",F_GETOWN);
  printf("  F_SETSIG : constant Interfaces.C.Int := %d; --\n",F_SETSIG);
  printf("  F_GETSIG : constant Interfaces.C.Int := %d; --\n",F_GETSIG);
  
  printf("  SEEK_SET : constant Interfaces.C.Int := %d; -- absolute position\n",SEEK_SET);
  printf("  SEEK_CUR : constant Interfaces.C.Int := %d; -- offset from current position\n",SEEK_CUR);
  printf("  SEEK_END : constant Interfaces.C.Int := %d; -- offset from end of file\n",SEEK_END);  
  
  printf("end C_Constants;\n");
  return 0;      
}

