 
  
//#include <sys/types.h>
//#include <sys/wait.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/fcntl.h>

int	main() {

  printf("-- Autogenerated file. Do not Edit! Change in c_contants.c instead, \n\n");
  printf("with Interfaces.C;\n\n");
  printf("package C_Constants is\n");
  printf("  O_RDONLY : constant Interfaces.C.Int := %d;\n",O_RDONLY);
  printf("  O_WRONLY : constant Interfaces.C.Int := %d;\n",O_WRONLY);
  printf("  O_RDWR   : constant Interfaces.C.Int := %d;\n",O_RDWR);
  printf("end C_Constants;\n");
  return 0;      
}

