# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.


#This file is manually maintained in the SattStore world!

package ifneeded ART_Definitions 1.0 [list source [file join $dir p_art_definitions.tcl]]
#package ifneeded Ada_Front_End_Usage 9.6 [list source [file join $dir p_ada_frontend_usage.tcl]]
package ifneeded Get_Opt 1.0 [list source [file join $dir p_get_opt.tcl]]
#package ifneeded Idf_Export_Utils 1.0 [list source [file join $dir p_idf_export_utils.tcl]]
package ifneeded Repo_Utils 1.0 [list source [file join $dir p_repo_utils.tcl]]
