-----------------------------------------------------
-- This file is AUTOGENERATED by                     
-- /home/bnl/bnlbot/botstart/bot-1-1/script/tcl/make_table_package.tcl at                                       
--9.6-10510                                          
----CHANGES HERE WILL BE LOST NEXT GENERATE!!!!----- 
-----------DO NOT EDIT THIS FILE!!!!---------------- 
-----------------------------------------------------



pragma Warnings(Off);
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Sattmate_Types, Sattmate_Calendar, Sql, Simple_List_Class;

package Table_Anonrunners is

  use Sattmate_Types, Sattmate_Calendar;

  type Data_Type is record
      Marketid :    String (1..11) := (others => ' ') ; -- Primary Key
      Selectionid :    Integer_4  := 0 ; -- Primary Key
      Ixxlupd :    String (1..15) := (others => ' ') ; --
      Ixxluts :    Time_Type  := Time_Type_First ; --
  end record;
  Empty_Data : Table_Anonrunners.Data_Type;
  -- 
  -- Table name as string 
  --
  Table_Anonrunners_Name : constant String := "ANONRUNNERS";
  Table_Anonrunners_Set_Name : constant String := "ANONRUNNERS_SET";
  Table_Anonrunners_Row_Name : constant String := "ANONRUNNERS_ROW";
  -- 
  -- Column names as strings 
  --
  Marketid_Name : constant String := "MARKETID";
  Selectionid_Name : constant String := "SELECTIONID";
  Ixxlupd_Name : constant String := "IXXLUPD";
  Ixxluts_Name : constant String := "IXXLUTS";
  -- 
  -- Column names as enumerator literals 
  --
  type Column_Type is (
        Marketid,
        Selectionid,
        Ixxlupd,
        Ixxluts);

  package Anonrunners_List_Pack is new Simple_List_Class(Table_Anonrunners.Data_Type);

  -- Procedures for DBMS DEF
  -- Primary key
  function Get(Stm : in Sql.Statement_Type) return Table_Anonrunners.Data_Type;
  --------------------------------------------
  procedure Read(Data       : in out Table_Anonrunners.Data_Type;
                 End_Of_Set : in out Boolean);
  --------------------------------------------
  function Is_Existing(Marketid : String;
                       Selectionid : Integer_4) return Boolean;
  --------------------------------------------
  function Get(Marketid : String;
                       Selectionid : Integer_4) return Table_Anonrunners.Data_Type;
  --------------------------------------------

  procedure Read_List(Stm  : in     Sql.Statement_Type;
                      List : in out Anonrunners_List_Pack.List_Type;
                      Max  : in     Integer_4 := Integer_4'Last);
  --------------------------------------------
  procedure Read_All(List  : in out Anonrunners_List_Pack.List_Type;
                     Order : in     Boolean := False;
                     Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------
  procedure Delete(Data : in Table_Anonrunners.Data_Type);
  --------------------------------------------
  procedure Update(Data : in out Table_Anonrunners.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  procedure Insert(Data : in out Table_Anonrunners.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  procedure Delete_Withcheck(Data : in Table_Anonrunners.Data_Type);
  --------------------------------------------
  procedure Update_Withcheck(Data : in out Table_Anonrunners.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  -- Primary keys, when several fields

  procedure Read_I1_Marketid(Data  : in     Table_Anonrunners.Data_Type;
                       List  : in out Anonrunners_List_Pack.List_Type;
                       Order : in     Boolean := False;
                       Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------

  procedure Delete_I1_Marketid(Data  : in     Table_Anonrunners.Data_Type);
  --------------------------------------------

  function Is_Existing_I1(
                 Marketid     : in String )      return Boolean;

  -- Index 

  procedure Read_Marketid(Data  : in     Table_Anonrunners.Data_Type;
                       List  : in out Anonrunners_List_Pack.List_Type;
                       Order : in     Boolean := False;
                       Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------

  procedure Read_One_Marketid(Data       : in out Table_Anonrunners.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  function Count_Marketid(Data : Table_Anonrunners.Data_Type) return Integer_4;
  --------------------------------------------


  procedure Delete_Marketid(Data  : in     Table_Anonrunners.Data_Type);
  --------------------------------------------


  -- Procedures for all DBMS

  function To_String(Data : in Table_Anonrunners.Data_Type) return String;

end Table_Anonrunners ;
