

-- Autogenerated by /home/bnl/bnlbot/botstart/bot-1-0/script/bash/create_revision_info.bash 
with Sattmate_Types; use Sattmate_Types;
package Bot_Svn_Info is 
  Revision : constant Integer_4 :=  818
  ; -- intentionally on this line!
end Bot_Svn_Info;

